# Generated by Django 3.1.6 on 2021-03-24 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='age',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
